### ISSUE TITLE
Netiquette.download.recipe

### ISSUE THREAD

**Issue by blackthroat** [autopkg/zentral-recipes#18]
The search pattern finds the latest version (which is hosted on GitHub), but latest does not exist in the Bitbucket repo.

```
 'RE_PATTERN': '(?P<dl_filename>(Netiquette_(\\d*\\.?)*).zip)',
 'SEARCH_URL': 'https://objective-see.com/products/netiquette.html',
 'verbose': 3}
URLTextSearcher
{'Input': {'re_pattern': '(?P<dl_filename>(Netiquette_(\\d*\\.?)*).zip)',
           'result_output_var_name': 'dl_filename',
           'url': 'https://objective-see.com/products/netiquette.html'}}
URLTextSearcher: Found matching text (dl_filename): Netiquette_1.2.0.zip
{'Output': {'dl_filename': 'Netiquette_1.2.0.zip'}}
URLDownloader
{'Input': {'CHECK_FILESIZE_ONLY': True,
           'url': 'https://bitbucket.org/objective-see/deploy/downloads/Netiquette_1.2.0.zip'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 177, in execute_curl
    errors=errors,
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://bitbucket.org/objective-see/deploy/downloads/Netiquette_1.2.0.zip', '--fail', '--output', '/Users/ladmin/Library/AutoPkg/Cache/com.github.zentralpro.download.netiquette/downloads/tmp6oceacn2']' returned non-zero exit status 22.
```

Perhaps switch the recipe to use `GitHubReleasesInfoProvider` processor? Or a polite nudge to Patrick Wardle?

**Comment by blackthroat** [comment]
Any interest with moving the download recipe to use the `GitHubReleasesInfoProvider` processor instead of `URLDownloader`?

**Comment by oliverweinm** [comment]
Hi @all,

I have made a PR changed this recipe to use the GithubReleasesInfoProvider instead of the URLTextSearcher (https://github.com/autopkg/zentral-recipes/pull/36)

Cheers
